#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailTemplateLibrary.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\HomePage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\HomePage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\HomePage.cshtml"
    using System.Text.Json;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\HomePage.cshtml"
    using EmailTemplateLibrary.Dashboard;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\HomePage.cshtml"
    using EmailTemplateLibrary.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\HomePage.cshtml"
    using EmailTemplateLibrary.Model;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class HomePage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









            
            #line 9 "..\..\Dashboard\Pages\HomePage.cshtml"
  
    Layout = new LayoutPage();


            
            #line default
            #line hidden
WriteLiteral(@"
<div class=""container"">
    <h2>Templates</h2>
    <p>Edit view or delete templates</p>
    
    <p>
        <button type=""button"" class=""btn btn-success"" id=""newTemplate"">
            New Template
        </button>
    </p>
    <table class=""table table-striped"">
        <thead>
            <tr>
                <th>Template Key</th>
                <th>Last Modified</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

");


            
            #line 33 "..\..\Dashboard\Pages\HomePage.cshtml"
             foreach (Template t in Templates)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n                        <h5>");


            
            #line 37 "..\..\Dashboard\Pages\HomePage.cshtml"
                       Write(t.TemplateKey);

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                    </td>\r\n                    <td>\r\n                     " +
"   <span>Last modified: ");


            
            #line 40 "..\..\Dashboard\Pages\HomePage.cshtml"
                                        Write(t.Modified);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </td>\r\n                    <td>\r\n                   " +
"     <button type=\"button\" class=\"btn btn-primary viewTemplate\" data-templatekey" +
"=\"");


            
            #line 43 "..\..\Dashboard\Pages\HomePage.cshtml"
                                                                                                Write(t.TemplateKey);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            View / Edit\r\n                        </button>\r\n " +
"                   </td>\r\n                    <td>\r\n                        <but" +
"ton type=\"button\" class=\"btn btn-danger deleteTemplate\" data-templatekey=\"");


            
            #line 48 "..\..\Dashboard\Pages\HomePage.cshtml"
                                                                                                 Write(t.TemplateKey);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Delete\r\n                        </button>\r\n      " +
"              </td>\r\n                </tr>\r\n");


            
            #line 53 "..\..\Dashboard\Pages\HomePage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </tbody>
    </table>
    <div class=""modal fade"" id=""viewTemplateModal"">
        <input type=""hidden"" id=""isNewTeplate"" value=""false""/>
        <div class=""modal-dialog modal-xl"">
            <div class=""modal-content"">
                <div class=""modal-header"">
                    <h4 class=""modal-title"">Edit</h4>
                    <button type=""button"" class=""close"" data-dismiss=""modal"">&times;</button>
                </div>

                <!-- Modal body -->
                <div class=""modal-body"">
                    <div class=""form-group"">
                        <label for=""templateKeyInput"">Template Key:</label>
                        <input id=""templateKeyInput"" type=""text"" class=""form-control"" value=""""/>
                        <h5>Template</h5>
                        <textarea class=""form-control"" rows=""5"" id=""templateTextInput""></textarea>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class=""modal-footer"">
                    <button id=""saveNewTemplate"" type=""button"" class=""btn btn-primary"" data-dismiss=""modal"">Save</button>                    
                    <button type=""button"" class=""btn btn-danger"" data-dismiss=""modal"">Close</button>
                </div>

            </div>
        </div>
    </div>
");


            
            #line 84 "..\..\Dashboard\Pages\HomePage.cshtml"
      

            
            #line default
            #line hidden
WriteLiteral("        <script>\r\n            let librarytemplates = ");


            
            #line 86 "..\..\Dashboard\Pages\HomePage.cshtml"
                              Write(Html.Raw(TemplatesJson));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        </script>\r\n");


            
            #line 88 "..\..\Dashboard\Pages\HomePage.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("</div>");


        }
    }
}
#pragma warning restore 1591
