name: Publish Packages

on:
  push:
    branches: [ master ] 

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), 'releasetonuget') == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish EmailTemplateLibrary
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
          PROJECT_FILE_PATH: src/EmailTemplateLibrary/EmailTemplateLibrary.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish EmailTemplateLibrary.AspNetCore
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
          PROJECT_FILE_PATH: src/EmailTemplateLibrary.AspNetCore/EmailTemplateLibrary.AspNetCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish EmailTemplateLibrary.Storage.Mongo
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
          PROJECT_FILE_PATH: src/EmailTemplateLibrary.Storage.Mongo/EmailTemplateLibrary.Storage.Mongo.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
